import type { ThemeMDXComponents, LayoutRegistry } from '../../theme/types'
import type { ResolvedSlideAddons, SlideAddonDefinition } from '../types'

// @ts-expect-error -- virtual module generated by slidev-react:addons Vite plugin
import activeAddons from 'virtual:slidev-react/active-addons'

const addonMap = new Map(activeAddons.definitions.map((addon) => [addon.id, addon]))

function normalizeAddonIds(addonIds?: string[]) {
  return [...new Set((addonIds ?? []).map((addonId) => addonId.trim()).filter(Boolean))]
}

function mergeLayouts(definitions: SlideAddonDefinition[]): LayoutRegistry {
  return definitions.reduce<LayoutRegistry>(
    (layouts, definition) => ({
      ...layouts,
      ...definition.layouts,
    }),
    {},
  )
}

function mergeMdxComponents(definitions: SlideAddonDefinition[]): ThemeMDXComponents {
  return definitions.reduce<ThemeMDXComponents>(
    (components, definition) => ({
      ...components,
      ...definition.mdxComponents,
    }),
    {},
  )
}

export function listRegisteredAddons() {
  return activeAddons.definitions.slice()
}

export function resolveAddonDefinitions(addonIds?: string[]) {
  const normalizedAddonIds = normalizeAddonIds(addonIds)
  if (normalizedAddonIds.length === 0) {
    return activeAddons.definitions.slice()
  }

  return normalizedAddonIds
    .map((addonId) => addonMap.get(addonId))
    .filter((addon): addon is SlideAddonDefinition => Boolean(addon))
}

export function resolveSlideAddons(addonIds?: string[]): ResolvedSlideAddons {
  const definitions = resolveAddonDefinitions(addonIds)

  return {
    definitions,
    providers: definitions
      .map((definition) => definition.provider)
      .filter((provider): provider is NonNullable<typeof provider> => Boolean(provider)),
    layouts: mergeLayouts(definitions),
    mdxComponents: mergeMdxComponents(definitions),
  }
}
